export const types = {
  SEND_REQUEST_REGISTER: 'SEND_REQUEST_REGISTER',
  SEND_REQUEST_REGISTER_SUCCESS: 'SEND_REQUEST_REGISTER_SUCCESS',
  SEND_REQUEST_REGISTER_FAILURE: 'SEND_REQUEST_REGISTER_FAILURE',
  CLEAR_REQUEST_REGISTER: 'CLEAR_REQUEST_REGISTER',

  SEND_REQUEST_LOGIN: 'SEND_REQUEST_LOGIN',
  SEND_REQUEST_LOGIN_SUCCESS: 'SEND_REQUEST_LOGIN_SUCCESS',
  SEND_REQUEST_LOGIN_FAILURE: 'SEND_REQUEST_LOGIN_FAILURE',
  CLEAR_REQUEST_LOGIN: 'CLEAR_REQUEST_LOGIN',

  SEND_REQUEST_NOTIFICATION: 'SEND_REQUEST_NOTIFICATION',
  SEND_REQUEST_NOTIFICATION_SUCCESS: 'SEND_REQUEST_NOTIFICATION_SUCCESS',
  SEND_REQUEST_NOTIFICATION_FAILURE: 'SEND_REQUEST_NOTIFICATION_FAILURE',
  CLEAR_REQUEST_NOTIFICATION: 'CLEAR_REQUEST_NOTIFICATION',

  SEND_REQUEST_FORGOT_PASSWORD: 'SEND_REQUEST_FORGOT_PASSWORD',
  SEND_REQUEST_FORGOT_PASSWORD_SUCCESS: 'SEND_REQUEST_FORGOT_PASSWORD_SUCCESS',
  SEND_REQUEST_FORGOT_PASSWORD_FAILURE: 'SEND_REQUEST_FORGOT_PASSWORD_FAILURE',
  CLEAR_REQUEST_FORGOT_PASSWORD: 'CLEAR_REQUEST_FORGOT_PASSWORD',

  SEND_REQUEST_ADD_BILL: 'SEND_REQUEST_ADD_BILL',
  SEND_REQUEST_ADD_BILL_SUCCESS: 'SEND_REQUEST_ADD_BILL_SUCCESS',
  SEND_REQUEST_ADD_BILL_FAILURE: 'SEND_REQUEST_ADD_BILL_FAILURE',
  CLEAR_REQUEST_ADD_BILL: 'CLEAR_REQUEST_ADD_BILL',

  SEND_REQUEST_GET_ALL_BILLS: 'SEND_REQUEST_GET_ALL_BILLS',
  SEND_REQUEST_GET_ALL_BILLS_SUCCESS: 'SEND_REQUEST_GET_ALL_BILLS_SUCCESS',
  SEND_REQUEST_GET_ALL_BILLS_FAILURE: 'SEND_REQUEST_GET_ALL_BILLS_FAILURE',
  CLEAR_REQUEST_GET_ALL_BILLS: 'CLEAR_REQUEST_GET_ALL_BILLS',

  SEND_REQUEST_GET_BILL_DETAIL: 'SEND_REQUEST_GET_BILL_DETAIL',
  SEND_REQUEST_GET_BILL_DETAIL_SUCCESS: 'SEND_REQUEST_GET_BILL_DETAIL_SUCCESS',
  SEND_REQUEST_GET_BILL_DETAIL_FAILURE: 'SEND_REQUEST_GET_BILL_DETAIL_FAILURE',
  CLEAR_REQUEST_GET_BILL_DETAIL: 'CLEAR_REQUEST_GET_BILL_DETAIL',

  SEND_REQUEST_IS_PHYSICALLY_SUBMITTED: 'SEND_REQUEST_IS_PHYSICALLY_SUBMITTED',
  SEND_REQUEST_IS_PHYSICALLY_SUBMITTED_SUCCESS:
    'SEND_REQUEST_IS_PHYSICALLY_SUBMITTED_SUCCESS',
  SEND_REQUEST_IS_PHYSICALLY_SUBMITTED_FAILURE:
    'SEND_REQUEST_IS_PHYSICALLY_SUBMITTED_FAILURE',
  CLEAR_REQUEST_IS_PHYSICALLY_SUBMITTED:
    'CLEAR_REQUEST_IS_PHYSICALLY_SUBMITTED',

  SEND_REQUEST_REMINDER: 'SEND_REQUEST_REMINDER',
  SEND_REQUEST_REMINDER_SUCCESS: 'SEND_REQUEST_REMINDER_SUCCESS',
  SEND_REQUEST_REMINDER_FAILURE: 'SEND_REQUEST_REMINDER_FAILURE',
  CLEAR_REQUEST_REMINDER: 'CLEAR_REQUEST_REMINDER',

  SEND_REQUEST_CHANGE_STATUS: 'SEND_REQUEST_CHANGE_STATUS',
  SEND_REQUEST_CHANGE_STATUS_SUCCESS: 'SEND_REQUEST_CHANGE_STATUS_SUCCESS',
  SEND_REQUEST_CHANGE_STATUS_FAILURE: 'SEND_REQUEST_CHANGE_STATUS_FAILURE',
  CLEAR_REQUEST_CHANGE_STATUS: 'CLEAR_REQUEST_CHANGE_STATUS',

  SEND_REQUEST_GET_DASHBOARD_DATA: 'SEND_REQUEST_GET_DASHBOARD_DATA',
  SEND_REQUEST_GET_DASHBOARD_DATA_SUCCESS:
    'SEND_REQUEST_GET_DASHBOARD_DATA_SUCCESS',
  SEND_REQUEST_GET_DASHBOARD_DATA_FAILURE:
    'SEND_REQUEST_GET_DASHBOARD_DATA_FAILURE',
  CLEAR_REQUEST_GET_DASHBOARD_DATA: 'CLEAR_REQUEST_GET_DASHBOARD_DATA',

  SEND_REQUEST_ADD_SUPER_ADMIN: 'SEND_REQUEST_GET_DASHBOARD_DATA',
  SEND_REQUEST_ADD_SUPER_ADMIN_SUCCESS:
    'SEND_REQUEST_GET_DASHBOARD_DATA_SUCCESS',
  SEND_REQUEST_ADD_SUPER_ADMIN_FAILURE:
    'SEND_REQUEST_GET_DASHBOARD_DATA_FAILURE',
  CLEAR_REQUEST_ADD_SUPER_ADMIN: 'CLEAR_REQUEST_GET_DASHBOARD_DATA',

  SET_TOKEN: 'SET_TOKEN',
  GET_TOKEN: 'GET_TOKEN',
};
