export const types = {

    SEND_REQUEST_REGISTER: 'SEND_REQUEST_REGISTER',
    SEND_REQUEST_REGISTER_SUCCESS: 'SEND_REQUEST_REGISTER_SUCCESS',
    SEND_REQUEST_REGISTER_FAILURE: 'SEND_REQUEST_REGISTER_FAILURE',
    CLEAR_REQUEST_REGISTER: 'CLEAR_REQUEST_REGISTER',

    SEND_REQUEST_LOGIN: 'SEND_REQUEST_LOGIN',
    SEND_REQUEST_LOGIN_SUCCESS: 'SEND_REQUEST_LOGIN_SUCCESS',
    SEND_REQUEST_LOGIN_FAILURE: 'SEND_REQUEST_LOGIN_FAILURE',
    CLEAR_REQUEST_LOGIN: 'CLEAR_REQUEST_LOGIN',

    SEND_REQUEST_NOTIFICATION: 'SEND_REQUEST_NOTIFICATION',
    SEND_REQUEST_NOTIFICATION_SUCCESS: 'SEND_REQUEST_NOTIFICATION_SUCCESS',
    SEND_REQUEST_NOTIFICATION_FAILURE: 'SEND_REQUEST_NOTIFICATION_FAILURE',
    CLEAR_REQUEST_NOTIFICATION: 'CLEAR_REQUEST_NOTIFICATION',

};